export const SELECIONA_LISTA_PESQUISA = 'SELECIONA_LISTA_PESQUISA'
export const STATUS_INICIAL_LISTA_PESQUISA = 'STATUS_INICIAL_LISTA_PESQUISA'
export const ADD_PESQUISA      = 'ADD_PESQUISA'
export const DELETE_PESQUISA   = 'DELETE_PESQUISA'
export const ATUALIZA_PESQUISA = 'ATUALIZA_PESQUISA'
export const CLEAN_PESQUISA    = 'CLEAN_PESQUISA'
export const DONE_PESQUISA    =   'DONE_PESQUISA'
export const PEDING_PESQUISA    = 'PEDING_PESQUISA'
export const PROCURA_TAREFA    = 'PROCURA_TAREFA'
export const GET_DESCRIPTION   = 'GET_DESCRIPTION'



